### ISSUE TITLE
相关问题咨询

### ISSUE THREAD

**Issue by liqingrui666** [stevenjoezhang/hass-iotbull#1]
请问需要把获取的API参数添加到文件变量吗？我在HA里添加你的插件后，输入账号密码后，就不能进行任何操作了。

**Comment by stevenjoezhang** [comment]
不需要，输入账号密码之后会自动登录。你可以检查一下 Home Assistant 的日志，看看有没有报错。因为我只用我自己的账号测试过，可能有一些逻辑没有处理。

**Comment by liqingrui666** [comment]
Logger: root
Source: custom_components/bull/api.py:157 
Integration: Bull IoT ([documentation](https://github.com/stevenjoezhang/iotbull/), [issues](https://github.com/stevenjoezhang/iotbull/issues)) 
First occurred: 19:41:56 (2 occurrences) 
Last logged: 19:45:25

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/config/custom_components/bull/api.py", line 157, in on_message
    if db["method"] == "thing.properties":
KeyError: 'method'

**Comment by stevenjoezhang** [comment]
好的，我发现我的日志里面也有这个报错，应该是 mqtt 发的消息格式被调整了……我再抓包研究一下

**Comment by stevenjoezhang** [comment]
可能和设备类型也有关系？我目前是适配了 G27 单火的开关，因为家里装修用的全是这款……早知道公牛的协议这么坑，就买小米这种开放协议的了

**Comment by liqingrui666** [comment]
难怪，我是用的智能wifi插座。你那个单火开关好像可以直接添加到米家里。

**Comment by stevenjoezhang** [comment]
那个好像是给小爱音箱控制，但不是直接走米家的协议。你要改代码的话是改这里：
https://github.com/stevenjoezhang/hass-iotbull/blob/c23566de4d2ff1a40a58b63ca32b2f5085a2fb0e/custom_components/bull/api.py#L141
不同设备的 devType 是不一样的，得抓包看看。我这里写的 devType 为 2 就是这个开关

**Comment by liqingrui666** [comment]
我抓包看到我的是0，但是我觉得应该不止一个参数不一样，就懒得试了，不过还是谢谢的分享了！

**Comment by Arthurvermouth** [comment]
你好，请问下我可以正常添加开关到home assistant中，可以通过Ha关闭或者开启灯泡，但是使用物理开关关闭或开启却并不改变状态，是我哪里没有设置好吗

**Comment by stevenjoezhang** [comment]
改变状态是靠订阅 MQTT 消息，如果握手失败的话，就会出现状态不同步的问题。你可以看看 Home assistant 日志里面有没有报错。我自己这段时间不在家，所以还没法拿自家的设备 debug……

**Comment by Arthurvermouth** [comment]
感谢！没事我的设备也不在手边，之后再再发日志来请教

**Comment by jerryye0** [comment]
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/bull/api.py:21
Integration: Bull IoT (documentation, issues)
First occurred: 09:05:35 (4 occurrences)
Last logged: 10:41:08

Error setting up entry 13586632094 for bull
Traceback (most recent call last):
  File "/var/packages/HomeAssistant/target/lib/python3.11/site-packages/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/HomeAssistant/home/.homeassistant/custom_components/bull/__init__.py", line 20, in async_setup_entry
    await bull_api.async_get_devices_list()
  File "/var/packages/HomeAssistant/home/.homeassistant/custom_components/bull/api.py", line 137, in async_get_devices_list
    self.parse_devices(res)
  File "/var/packages/HomeAssistant/home/.homeassistant/custom_components/bull/api.py", line 142, in parse_devices
    device = BullDevice(self, info)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/HomeAssistant/home/.homeassistant/custom_components/bull/api.py", line 21, in __init__
    self._value: int = info["property"][self._identifier]["value"]
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'PowerSwitch_1'

**Comment by jerryye0** [comment]
我全都是单火的开关  同样操作不了

**Comment by stevenjoezhang** [comment]
我自己的账号复现不了这个问题（`property` 里面的键名和 `elementIdentifier` 都是对应的，不报错）
你可以试试按这个 commit 更新，然后检查 debug 日志里面请求到的 json 格式设备列表，也可以贴上来我分析一下 https://github.com/stevenjoezhang/hass-iotbull/commit/1b82ee3e59f8e48dd75ecef371bd5e30a6d64a46

**Comment by cloudGrin** [comment]
https://github.com/stevenjoezhang/hass-iotbull/blob/0d7145fe8b9a7932e78a3ea6bbe0f130e3036112/custom_components/bull/api.py#L157

这里的代码在wifi插座设备里切换状态会报错，要增加一下判断

if "method" in db

**Comment by stevenjoezhang** [comment]
@jerryye0 OK，我定位到问题了。是不是有一个G27智能一位无线开关(zigbee)，它是和一个G27智能三位开关(单火/zigbee)中的书房照明灯联动的？可能要把它排除掉

**Comment by stevenjoezhang** [comment]
我之后再改改～

**Comment by stevenjoezhang** [comment]
这个问题应该解决了，更新一下就行。有其他问题欢迎新开 issue
