### ISSUE TITLE
switch_family_error

### ISSUE THREAD

**Issue by Resurrection2981** [stevenjoezhang/hass-iotbull#5]
日志: homeassistant.config_entries
来源: config_entries.py:575
首次发生: 12:51:34 (1 全部发生)
上次记录: 12:51:34

Error setting up entry xxxxxxxxxxxxx for bull
Traceback (most recent call last):
  File "/config/custom_components/bull/api.py", line 340, in async_make_request
    res = json.loads(response.content)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/bull/api.py", line 173, in async_switch_family
    res = await self.async_make_request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bull/api.py", line 350, in async_make_request
    await self.async_refresh_access_token()
  File "/config/custom_components/bull/api.py", line 145, in async_refresh_access_token
    res = await self.async_make_request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bull/api.py", line 357, in async_make_request
    res = await self.async_make_request(method, path, content_type, header, body, True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bull/api.py", line 342, in async_make_request
    raise Exception("connection_failed")
Exception: connection_failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bull/__init__.py", line 20, in async_setup_entry
    await bull_api.async_get_all_devices_list()
  File "/config/custom_components/bull/api.py", line 204, in async_get_all_devices_list
    await self.async_switch_family(familyId)
  File "/config/custom_components/bull/api.py", line 178, in async_switch_family
    raise Exception("switch_family_error")
Exception: switch_family_error

**Comment by stevenjoezhang** [comment]
修复了一下： https://github.com/stevenjoezhang/hass-iotbull/commit/5ad891f80e441c0dc193fd6e9f258235cc150a24
你可以更新之后看有没有解决

**Comment by Resurrection2981** [comment]
没再遇到应该是解决了
